config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Add Routes:
  resources :playlists
  get '/playlists/add_one', to: 'playlists#add_one'

  resources :playlist_tracks, only: :destroy

  get '/auth/spotify/callback', to: 'users#spotify'

  resources :tracks

  post 'playlist_tracks/:playlist_id/:spotify_id', to: 'playlist_tracks#create', as: :playlist_tracks
  post 'playlist/:id/push', to: 'playlists#push', as: :spotify_playlist

  get '/search', to: 'tracks#search'
  get '/enhanced_search', to: 'tracks#enhanced_search'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  has_many :playlist_tracks, dependent: :destroy
  has_many :tracks, through: :playlist_tracks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: { scope: :user_id }
end

app/models/playlist_track.rb
class PlaylistTrack < ApplicationRecord
  belongs_to :track
  belongs_to :playlist

  validates_uniqueness_of :track_id, :scope => [:playlist_id]
end

app/models/track.rb
class Track < ApplicationRecord
  has_many :playlist_tracks
  has_many :playlists, through: :playlist_tracks

  validates :spotify_id, presence: true, uniqueness: true
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :playlists, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  # app/controllers/application_controller.rb
  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

end

app/controllers/playlist_tracks_controller.rb
class PlaylistTracksController < ApplicationController
  before_action :set_playlist_track, only: [:destroy]

  def create
    # get selected playlist
    playlist = Playlist.find(params[:playlist_id])
    # get track
    spotify_track = RSpotify::Track.find(params[:spotify_id])

    if Track.find_by(spotify_id:params[:spotify_id]).nil?
      track = Track.new(
        spotify_id: spotify_track.id,
        name: spotify_track.name,
        artists: spotify_track.artists,
        track_image: spotify_track.album.images.first["url"],
        album: spotify_track.album.name,
        artists_genres: spotify_track.artists.first.genres.join(", "),
        preview_url: spotify_track.preview_url,
        acousticness: spotify_track.audio_features.acousticness,
        danceability: spotify_track.audio_features.danceability,
        duration_ms: spotify_track.audio_features.duration_ms,
        energy: spotify_track.audio_features.energy,
        instrumentalness: spotify_track.audio_features.instrumentalness,
        liveness: spotify_track.audio_features.liveness,
        loudness: spotify_track.audio_features.loudness,
        mode: spotify_track.audio_features.mode,
        speechiness: spotify_track.audio_features.speechiness,
        tempo: spotify_track.audio_features.tempo,
        valence: spotify_track.audio_features.valence,
        popularity: spotify_track.popularity,
        uri: spotify_track.uri
      )
      track.save
    else
      track = Track.find_by(spotify_id:params[:spotify_id])
    end

    # save track to playlist
    playlist_track = PlaylistTrack.create(playlist_id: playlist.id, track_id: track.id)
    if playlist_track.save
      flash.notice = "#{track.name} has been added to #{playlist.name}"
    else
      flash.alert = "#{track.name} could not be saved to #{playlist.name}"
    #   redirect_to "tracks/enhanced_search", notice: "#{track.name} has been added to #{playlist.name}"
    # else
    #   redirect_to "tracks/enhanced_search", alert: "#{track.name} could not be saved to #{playlist.name}"
    end
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @playlist_track.destroy
    redirect_to playlist_path(@playlist_track.playlist), notice: 'Track removed from playlist.'
  end

  private

  def set_playlist_track
    @playlist_track = PlaylistTrack.find(params[:id])
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: %i[show edit update destroy push]

  def index
    @playlists = current_user.playlists
  end

  def show
  end

  def new
    @playlist = Playlist.new
  end

  def create
    if user_signed_in?
      @playlist = Playlist.new(playlist_params)
      @playlist.user = current_user
      @playlist.save
      redirect_to playlist_path(@playlist)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @playlist.update(playlist_params)
    redirect_to playlist_path(@playlist)
  end

  def destroy
    @playlist.destroy
    redirect_to playlists_path, status: :see_other
  end

  def push
    user = RSpotify::User.find(session[:spotify_user]["id"])

    spotify_playlist = user.create_playlist!(@playlist.name)
    # we extract the IDs of each track of the playlist:
    tracks_ids = @playlist.tracks.pluck(:spotify_id)
    # tracks becomes an array of tracks because tracks_ids is an array of IDs:
    tracks = RSpotify::Track.find(tracks_ids)
    if spotify_playlist.add_tracks!(tracks)
      flash.notice = "Your playlist #{@playlist.name} has been added to Spotify"
    else
      flash.alert = "Your playlist #{@playlist.name} could not be added to Spotify"
    end
    redirect_back(fallback_location: root_path)
  end

private

  def set_playlist
    @playlist = Playlist.find(params[:id])
  end

  def playlist_params
    params.require(:playlist).permit(:name, :description, :photo)
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: %i[index]

  def index
    @playlists = Playlist.where(user: current_user)
  end

  def search
    # binding.pry
    if params[:query].present?
    @tracks = RSpotify::Track.search(params[:query])
    end

    respond_to do |format|
      format.html
      format.text { render partial: "tracks/list", locals: {tracks: @tracks}, formats: [:html] }
    end
  end

  def enhanced_search
    begin
      @recommendations = RSpotify::Recommendations.generate(
        limit: 12,
        seed_tracks: [params[:spotify_id]],
        target_acousticness: params[:acousticness],
        target_danceability: params[:danceability],
        target_energy: params[:energy],
        target_instrumentalness: params[:instrumentalness],
        target_liveness: params[:liveness],
        target_loudness: params[:loudness],
        target_speechiness: params[:speechiness],
        target_valence: params[:valence],
        target_popularity: params[:popularity]
      )
    rescue RestClient::TooManyRequests
      redirect_to root_path, alert: "Oops"
    end
    @playlists = Playlist.where(user: current_user)
  end

  private

  def set_track
    @track = RSpotify::Track.find(params[:query])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def spotify
    session[:spotify_user] = RSpotify::User.new(request.env['omniauth.auth'])
    redirect_to root_path, notice: "redirected"
    # Now you can access user's private data, create playlists and much more
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title

  content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]

  end

  def meta_description

  content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]

  end

  def meta_image

  meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])

  # little twist to make it work equally with an asset or a url

  meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ontrack</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <title><%= meta_title %></title>  <meta name="description" content="<%= meta_description %>">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />  <meta property="og:type" content="website" />  <meta property="og:url" content="<%= request.original_url %>" />  <meta property="og:image" content="<%= meta_image %>" />  <meta property="og:description" content="<%= meta_description %>" />  <meta property="og:site_name" content="<%= meta_title %>">

    <%= favicon_link_tag asset_path('Favicon.png') %>

  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<body class="home">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-sm-8 my-3">
        <div class="slogan row">
          <h1 class="title-text col-12 text-center">Find the music you love</h1>
        </div>
        <div data-controller="search-tracks">
          <%= form_with url: "#", method: :get, class: "d-flex flex-column align-items-center search-form", id: "search-form-home", html: {data: {search_tracks_target: "form"}} do |f| %>
            <div class="position-relative">
              <%= f.text_field :query,
                              class: "search-form d-flex mb-4",
                              id: "search-form-search",
                              placeholder: "Search for your track",
                              value: params[:query],
                              data: {
                                search_tracks_target: "input",
                                action: "keyup->search-tracks#update"
                              }
                              %>
              <i class="fa-solid fa-magnifying-glass position-absolute search-icon"></i>
            </div>
          <% end %>
          <%= render "tracks/list", tracks: @tracks %>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/playlists/_add_one.html.erb
<p id="dropdown-title">Add to playlist</p>
<% playlists.each do |playlist| %>
  <%= link_to playlist.name, playlist_tracks_path(playlist, track.id), data: {turbo_method: :post}, class: "dropdown-item" %>
<% end %>

app/views/playlists/_add_ref.html.erb
<p id="dropdown-title">Add to playlist</p>
<% playlists.each do |playlist| %>
  <%= link_to playlist.name, playlist_tracks_path(playlist, track.id), data: {turbo_method: :post}, class: "dropdown-item" %>
<% end %>

app/views/playlists/_form.html.erb
<%= simple_form_for (@playlist) do |f| %>
  <p><%= f.input :name, placeholder: "Your playlist name", label: false, class: "form-inline" %></p>
  <p><%= f.input :photo, as: :file, label: false, class: "form-inline" %></p>
  <p><%= f.input :description, placeholder: "Description", label: false, class: "form-inline" %></p>
  <p class="text-center"><%= f.submit "SUBMIT", class: "pink-btn" %></p>
<% end %>
<p class="text-center"><%= link_to "Back to your playlists", playlists_path, class: "text-60"%></p>

app/views/playlists/edit.html.erb
<div class="container">
  <h1> Edit playlist </h1>
      <div class="form-group">
        <%= render 'form', playlist: @playlist %>
      </div>
</div>

app/views/playlists/index.html.erb
<div class="container">
  <div class="container-header-flex">
    <div class="title">
      <h1>Playlists</h1>
    </div>
    <div class="create-playlist">
      <%= link_to 'Create playlist', new_playlist_path, class: "pink-btn-link" %>
    </div>
  </div>

  <div class="container-outer-flex">
    <% @playlists.each do |playlist| %>
      <div class="card-playlist">
        <%= link_to playlist_path(playlist) do %>
          <% if playlist.photo.present? %>
            <%= cl_image_tag playlist.photo.key, class: "playlist-card-image", alt: "Playlist Image" %>
          <% else %>
            <p class="playlist-card-image">No playlist image available</p>
          <% end %>
          <div class="card-playlist-infos">
            <div class="card-playlist-title">
              <h3><%= playlist.name %></h3>
            </div>
            <div class="card-playlist-description">
              <% if playlist.description? %>
                <p><%= playlist.description %></p>
              <% else %>
                <p><%= playlist.name %> was created by <%= current_user.email %> on <%= playlist.created_at.strftime('%B of %Y') %>.</p>
              <% end %>
            </div>
          </div>
        <% end %>
        <div class="edit-delete-btns">
          <%= link_to edit_playlist_path(playlist), class: "icon-btn" do %>
            <i class="fa-solid fa-pen-to-square"></i>
          <% end %>
          <%= link_to playlist_path(playlist), data: {turbo_method: :delete, turbo_confirm: "Do you want to delete your playlist?"}, class: "icon-btn" do %>
            <i class="fa-solid fa-trash"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/playlists/new.html.erb
<div class="container">
  <h1> Create a playlist </h1>
      <div class="form-group">
        <%= render 'form', playlist: @playlist %>
      </div>
</div>

app/views/playlists/show.html.erb
<div class="container">
<div class="row justify-content-center">

  <div class="playlist_header">

    <div class="playlist_image_container">
      <% if @playlist.photo.present? %>
        <%= cl_image_tag @playlist.photo.key, class: "playlist_image", alt: "Playlist Image" %>
      <% else %>
        <p>No playlist image available</p>
      <% end %>
    </div>

    <div class="text-btn-div">
      <div class="page_title">
        <h1><%= @playlist.name %></h1>
        <% if @playlist.description? %>
          <p><%= @playlist.description %></p>
        <% else %>
          <p><%= @playlist.name %> was created by <%= current_user.email %> on <%= @playlist.created_at.strftime('%B of %Y') %>.</p>
        <% end %>
      </div>

      <div class="playlist_btns">
        <i class="fa-solid fa-pen-to-square text-white"></i><%= link_to 'Edit', edit_playlist_path, class:"text-white text-btn " %>
        <i class="fa-solid fa-trash text-white"></i><%= link_to "Delete", playlist_path(@playlist), data: {turbo_method: :delete, turbo_confirm: "Do you want to delete your playlist?"}, class:"text-white text-btn "%>
      </div>
    </div>
  </div>
  <div class="container-btn">
    <div class="pink-btn-add-to-spotify">
      <%= link_to 'Add playlist to', spotify_playlist_path, data: {turbo_method: :post}, class:"text-white" %> <%= image_tag ("spotify-48.png"), class: "spotify-icon" %>
    </div>
  </div>

  <div class="playlist-body">
    <ul>
      <% @playlist.tracks.each do |track| %>
        <li class="list-group-item">
          <div class="card track-card" id="playlist-card">
            <div class="card-body d-flex">
              <div class="flex-grow-1">
                <iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/<%= track.spotify_id %>?utm_source=generator" width="100%" height="80" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
              </div>
                <div class="p-2 align-self-center">
                <% playlist_track = PlaylistTrack.find_by(track:track, playlist:@playlist) %>
                  <%= link_to playlist_track_path(playlist_track), data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to remove this track from the playlist?' }, class: 'icon-btn' do %>
                    <i class="fa-solid fa-circle-xmark"></i>
                  <% end %>
                </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon align-items-center">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "OnTrack2.png" %>
    <% end %> 

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <%# User is signed in to our app %>
          <% if session[:spotify_user].nil? %>
            <%# User is not connected to Spotify %>
            <li class="nav-item">
              <%= link_to 'Connect with Spotify', '/auth/spotify', method: :post, class: "nav-link connect-button" %>
            </li>
            <li class="nav-item dropdown">
              <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= image_tag ("avatar.png"), class: "avatar", alt: "dropdown menu" %>
              </a>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <%# User is connected to Spotify %>
            <li class="d-none">
              <%= session[:spotify_user] %>
            </li>
            <li class="nav-link create-playlist-btn">
              <i class="fa-solid fa-magnifying-glass position-icon text-white"></i> <%= link_to 'Search ', root_path, class: "search-nav"%>
            </li>
            <li class="nav-link all-playlists-btn">
              <i class="fa-solid fa-music playlist-icon text-white"></i><%= link_to "Playlists", playlists_path, class: "playlist-nav"%>
            </li>

            <li class="nav-item dropdown">
              <% if session[:spotify_user]["images"].blank? %>
                <%# User has no Spotify profile picture %>
                <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <%= image_tag ("avatar.png"), class: "avatar", alt: "dropdown menu" if session[:spotify_user] %>
                </a>
              <% else %>
                <%# User has a Spotify profile picture %>
                <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <%= image_tag (session[:spotify_user]["images"][1]["url"]), class: "avatar", alt: "dropdown menu" if session[:spotify_user] %>
                </a>
              <% end %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
            </li>
          <% end %>
        <% else %>
          <%# User is not signed in to our app %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link pink-btn text-center", id: "login-btn" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tracks/_list.html.erb
<div data-search-tracks-target="list">
  <% if @tracks.present? %>
    <ul>
    <% @tracks.each do |track| %>
      <%= link_to({ controller: 'tracks', query: track.id }) do %>
        <div class="card track-card-search">
          <div class="card-body card-body-search">
              <%= image_tag (track.album.images.first["url"]), class: "cover" %>
              <div class="text-title">
                <%= "#{track.name}"%>
              </div>
              <div class="text-artist">
                <%= "#{track.artists[0].name}" %>
              </div>
          </div>
        </div>
      <% end %>
    <% end %>
    </ul>
  <% end %>
</div>

app/views/tracks/_range_sliders.html.erb
<div class="sliders-container">
  <h3>Let's set the mood</h3>
  <p>Based on the song you searched, we've made a vibe 😎 Adjust the levels based on your mood or simply continue.</p>

  <div class="sliders-mini-container">


    <%= form_with url: "/enhanced_search", method: "get" do |f| %>
      <%= f.hidden_field :spotify_id, value: @track.id %>
      <div class="slider-item">
        <%= f.label :acousticness, "acousticness", class: "form-label faders-label" %>
        <%= f.range_field :acousticness, class: "form-range faders-range", value: @track.audio_features.acousticness, in:0..1, step:0.0001 %>
      </div>
      <div class="slider-item">
        <%= f.label :danceability, "danceability", class: "form-label faders-label" %>
        <%= f.range_field :danceability, class: "form-range faders-range", value: @track.audio_features.danceability, in:0..1, step:0.0001 %>
      </div>
      <div class="slider-item">
        <%= f.label :energy, "energy", class: "form-label faders-label" %>
        <%= f.range_field :energy, class: "form-range faders-range", value: @track.audio_features.energy, in:0..1, step:0.0001 %>
      </div>
      <div class="slider-item">
        <%= f.label :instrumentalness, "instrumentalness", class: "form-label faders-label" %>
        <%= f.range_field :instrumentalness, class: "form-range faders-range", value: @track.audio_features.instrumentalness, in:0..1, step:0.0001 %>
      </div>
      <div class="slider-item">
        <%= f.label :liveness, "liveness", class: "form-label faders-label" %>
        <%= f.range_field :liveness, class: "form-range faders-range", value: @track.audio_features.liveness, in:0..1, step:0.0001 %>
      </div>
      <div class="slider-item">
        <%= f.label :loudness, "loudness", class: "form-label faders-label" %>
        <%= f.range_field :loudness, class: "form-range faders-range", value: @track.audio_features.loudness, in:-60..0, step:0.006 %>
      </div>
      <div class="slider-item">
        <%= f.label :speechiness, "speechiness", class: "form-label faders-label" %>
        <%= f.range_field :speechiness, class: "form-range faders-range", value: @track.audio_features.speechiness, in:0..1, step:0.0001 %>
      </div>
      <div class="slider-item">
        <%= f.label :valence, "valence", class: "form-label faders-label" %>
        <%= f.range_field :valence, class: "form-range faders-range", value: @track.audio_features.valence, in:0..1, step:0.0001 %>
      </div>
      <div class="slider-item">
        <%= f.label :popularity, "popularity", class: "form-label faders-label" %>
        <%= f.range_field :popularity, class: "form-range faders-range", value: @track.popularity, in:0..100, step:1 %>
      </div>
      <div class="slider-item d-flex justify-content-center">
        <%= f.submit "This is it!", class: "pink-btn"%>
      </div>
    <% end %>
  </div>
</div>

app/views/tracks/_search-bar.html.erb
<%= form_with url: search_path, method: :get, class: "d-flex search-form" do %>
<%= text_field_tag :query,
      nil,
      class: "form-control",
      id: "search-bar-corner",
      placeholder: "Search again?"
  %>
<%= submit_tag "Search", name: "", class: "d-none" %>
<% end %>

app/views/tracks/enhanced_search.html.erb
<div class="container">
  <div class="row justify-content-center">

  <div class="container-header-flex">
    <div class="title">
      <h1>Your Results</h1>
    </div>
    <div class="create-playlist">
      <%= link_to 'Refine Your Search', 'javascript:history.go(-1);', class: "pink-btn-link" %>
    </div>
  </div>

  <h3>The Vibe</h3>

    <ul>
      <li class="list-group-item">
        <iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/<%= params[:spotify_id] %>?utm_source=generator" width="100%" height="200" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
      </li>
    </ul>

  <h3>Tracks based on your pick</h3>

    <ul>
      <% @recommendations.tracks.each do |track| %>
        <% if track.id != params[:spotify_id] %>
          <li class="list-group-item">
          <div class="card track-card border-0">
            <div class="card-body d-flex">

              <div class="flex-grow-1">
                <iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/<%= track.id %>?utm_source=generator" width="100%" height="80" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
              </div>

              <div class="dropdown p-2 align-self-center">
                <button class="btn icon-btn" id="add-to-playlist" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="fa-solid fa-circle-plus"></i>
                </button>
                <ul class="dropdown-menu">
                  <%= render "playlists/add_one", playlists: @playlists, track: track %>
                </ul>
              </div>

            </div>
          </div>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/tracks/index.html.erb
<div class="container">
  <div class="row justify-content-center">

  <div class="container-header-flex">
    <div class="title">
      <h1>Your Results</h1>
    </div>
    <div class="add-reference-playlist">
      <div class="dropdown p-2 align-self-center">
      <button class="btn icon-btn" id="add-to-playlist" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="fa-solid fa-circle-plus"></i>
      </button>
      <ul class="dropdown-menu">
        <%= render "playlists/add_ref", playlists: @playlists, track: @track %>
      </ul>
    </div>
    </div>
  </div>

  <iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/<%= @track.id %>?utm_source=generator" width="100%" height="200" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>


  <div class="" data-controller="sliders" data-sliders-id-value="<%= @track.id %>">
    <div id="range_sliders">
      <%= render 'range_sliders', track: @track %>
    </div>
    <div id="search_results" data-sliders-target="results">
    </div>
  </div>

</div>